name: pening_repository_ngr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  just_the_tooltip: ^0.0.12
  provider: ^6.1.5

dev_dependencies:
  build_runner: ^2.6.0
  flutter_gen_runner: ^5.11.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
